/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_roan_kps_Title */

#ifndef _Included_me_roan_kps_Title
#define _Included_me_roan_kps_Title
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_roan_kps_Title
 * Method:    getMSNStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_roan_kps_Title_getMSNStatus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
