/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_roan_kps_Main */

#ifndef _Included_me_roan_kps_Main
#define _Included_me_roan_kps_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_roan_kps_Main
 * Method:    toTop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_roan_kps_Main_toTop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
