/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_roan_kps_Main_KeyInformation */

#ifndef _Included_me_roan_kps_Main_KeyInformation
#define _Included_me_roan_kps_Main_KeyInformation
#ifdef __cplusplus
extern "C" {
#endif
#undef me_roan_kps_Main_KeyInformation_serialVersionUID
#define me_roan_kps_Main_KeyInformation_serialVersionUID -8669938978334898443i64
#ifdef __cplusplus
}
#endif
#endif
