/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_roan_kps_Main_Key */

#ifndef _Included_me_roan_kps_Main_Key
#define _Included_me_roan_kps_Main_Key
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
